require("font-awesome/scss/font-awesome.scss")
require("./src/scss/main.scss");
//require("./components/blog/blog.js")
//require("./components/admin/admin.js")
//require("./components/post/post.js");
//require("./components/slides/slides.js");
require("./components/blog/blog.js");
//require("./components/admin/admin.actions.js");
//require("./components/post/post.actions.js");
//require("./components/slides/slides.actions.js");
//require("./components/todo/todo.actions.js");
//require("./components/mindmap/mindmap.actions.js");
